<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Drop check constraint generated by PostgreSQL for enum column
        DB::statement('ALTER TABLE rekrutmen.pelamars DROP CONSTRAINT IF EXISTS pelamars_status_check');
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // No need to restore old enum check
    }
};
